### ISSUE TITLE
Academics Pages not working with Admin

### ISSUE THREAD

**Issue by steven-king** [ASK-MEdia/bm-redesign#1]
When content updated here: http://institute.stg2.biblemesh.com/wp-admin/post.php?post=26&action=edit 

it is not reflected in changes here: http://institute.stg2.biblemesh.com/academics/

**Comment by glocal7** [comment]
Will be worked upon..

**Comment by glocal7** [comment]
Please check now..

**Comment by steven-king** [comment]
Churches is not working
http://institute.stg2.biblemesh.com/churches/
http://institute.stg2.biblemesh.com/wp-admin/post.php?post=24&action=edit

**Comment by glocal7** [comment]
Agreed, will get it in place.

**Comment by glocal7** [comment]
Agreed, will get it in place.

**Comment by glocal7** [comment]
Resolved...

Following pages are also now manageable from the backend:
http://institute.stg2.biblemesh.com/legal/
http://institute.stg2.biblemesh.com/helpfaq/
http://institute.stg2.biblemesh.com/churches/

**Comment by steven-king** [comment]
Thanks!
