### ISSUE TITLE
INSTITUTEL: Images question on programs

### ISSUE THREAD

**Issue by steven-king** [ASK-MEdia/bm-redesign#10]
How do I change out these different images on programs. They dont seem to be working with featured images.
http://institute.stg2.biblemesh.com/programs/

**Comment by glocal7** [comment]
Need more clarity on this.. Please help us understand the concern.

**Comment by steven-king** [comment]
From our conversation via skype...

We need them to have different, dynamic images. You can bill me for the hours to make that change.

doing dynamic images with 6 programs is lot easier; also the programs can be increased/ decreased at present.. (they are dynamic), but they are pulling 1 common image.. developer will evaluate and will come up with a solution

**Comment by glocal7** [comment]
You can change it easily now..
Go to 

Dashboard  Institute programs  Program details

Click on Edit and then change the Thumbnail image

![program details institute](https://cloud.githubusercontent.com/assets/22104231/18472291/202a7b22-79d4-11e6-8596-9f4bae6f5de2.jpg)
![p_2](https://cloud.githubusercontent.com/assets/22104231/18472303/3242ae9c-79d4-11e6-8b57-eac51893a9b9.jpg)
![p_3](https://cloud.githubusercontent.com/assets/22104231/18472305/372cf304-79d4-11e6-9968-04dd1db1976a.jpg)

**Comment by steven-king** [comment]
Looks good. thanks
