### ISSUE TITLE
INSTITUTE: Program list text change.

### ISSUE THREAD

**Issue by steven-king** [ASK-MEdia/bm-redesign#11]
Default state of drop downs should read “Select Program”
http://institute.stg2.biblemesh.com/programs/

**Comment by steven-king** [comment]
Also, Dropdowns Style is crowded on Firefox. Can you make wider?

**Comment by glocal7** [comment]
Firefox issue resolved.. Please review content update 'Select Program' as well

**Comment by steven-king** [comment]
Approved.
