### ISSUE TITLE
INSTITUTE: Faculty on a course not dispalying properly

### ISSUE THREAD

**Issue by steven-king** [ASK-MEdia/bm-redesign#12]
http://institute.stg2.biblemesh.com/institute_programs/high-school-dual-enrollment-one/

**Comment by glocal7** [comment]
Getting displayed.. we'll share the process for the same.

**Comment by steven-king** [comment]
I will check this when I get the screen shots on how to update/create Programs -- Courses  -- Faculty

**Comment by glocal7** [comment]
Hi Steven,

Here is the User manual, we can connect over Skype for better understanding.

Thanks!
[User_Manual_Sep_13.docx](https://github.com/ASK-MEdia/bm-redesign/files/469669/User_Manual_Sep_13.docx)

**Comment by steven-king** [comment]
WOrks! Great!
