### ISSUE TITLE
INSTITUTE: Header Images for Program

### ISSUE THREAD

**Issue by steven-king** [ASK-MEdia/bm-redesign#5]
Where does the header image come from on Programs? I can not seem to find it in the admin. It looks like featured image is not working
http://institute.stg2.biblemesh.com/institute_programs/union-university-master-of-christian-studies-mcs-38-credit-hours/
http://institute.stg2.biblemesh.com/wp-admin/post.php?post=265&action=edit

**Comment by glocal7** [comment]
Done, please try to use featured image now..

**Comment by steven-king** [comment]
Good. Thanks!
