### ISSUE TITLE
INSTITUTE: Instructor not appearing on Courses

### ISSUE THREAD

**Issue by steven-king** [ASK-MEdia/bm-redesign#8]
Instructor Does not appear on the Course See New Testament Greek 1
http://institute.stg2.biblemesh.com/wp-admin/post.php?post=267&action=edit

**Comment by glocal7** [comment]
Done, please review.

**Comment by steven-king** [comment]
Waiting till I understand how Programs - Courses and Faculty work together. At the moment I am not seeing one on the Union Program but that could be my fault in how it is connected/edited on the wp admin.

**Comment by glocal7** [comment]
User manual attached in issue #12

**Comment by steven-king** [comment]
works
