### ISSUE TITLE
INSTITUTE: Course syllabus link not working

### ISSUE THREAD

**Issue by steven-king** [ASK-MEdia/bm-redesign#9]
Upload of Syllabus section. Link is Very long and ugly. and Link does not work. It should Show the Title for the link text

**Comment by steven-king** [comment]
http://institute.stg2.biblemesh.com/institute_programs/union-university-masters-of-christian-studies-38-hours/

**Comment by glocal7** [comment]
Course syllabus link is working now..
URL can be managed from the URL section of the backend part itself..

**Comment by steven-king** [comment]
The link is pretty now but not working. Send me to a 404 page.

From here:
http://institute.stg2.biblemesh.com/institute_programs/union-university-masters-of-christian-studies-38-hours/

to here:

http://institute.stg2.biblemesh.com/institute_programs/union-university-masters-of-christian-studies-38-hours/268,%20,%20MCSGreek1syllabus%20Fall%202016,%20,%20,%20application/pdf,%20http:/institute.stg2.biblemesh.com/wp-content/uploads/sites/2/2016/09/MCSGreek1syllabus-Fall-2016.pdf

**Comment by glocal7** [comment]
It is working the link was empty.. we have attached a dummy pdf file to it now. Please review.

**Comment by steven-king** [comment]
looks good
